version: "3.9"

services:
  fastapi-app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/app  # Mount the whole backend directory for hot reload
    environment:
      - PYTHONPATH=/app
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 80 --reload --reload-dir /app
