// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver';
import assert from 'assert';

describe('test selenium ide', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('a', async function() {
    await driver.get("https://www.selenium.dev/selenium-ide/")
    await driver.manage().window().setRect({ width: 2010, height: 1170 })
    await driver.findElement(By.linkText("Docs")).click()
    assert(await driver.getTitle() == "Getting Started · Selenium IDE")
    // await driver.close()
  })
})
