// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import assert from 'assert'
import chrome from 'selenium-webdriver/chrome.js'

describe('Booking Summary Calculation', function() {
  this.timeout(60000)
  let driver
  let vars
  const BASE_URL = 'http://localhost:5173'
  
  // Global test account credentials from environment variables
  const globalTestEmail = process.env.EMAIL || 'globaltest1765533455848@example.com'
  const globalTestPassword = process.env.PASSWORD || 'TestAccount123!'

  async function loginWithGlobalAccount() {
    await driver.get(BASE_URL)
    
    // Check if already logged in
    try {
      await driver.get(`${BASE_URL}/flight`)
      await driver.sleep(2000)
      
      const currentUrl = await driver.getCurrentUrl()
      if (currentUrl.includes(BASE_URL) && !currentUrl.includes('auth0.com')) {
        try {
          await driver.findElement(By.css('img[alt*="Profile"], div[class*="rounded-full"]'))
          console.log('✓ User already logged in')
          return
        } catch (e) {
          // No profile, need to login
        }
      }
    } catch (e) {
      // Error checking, proceed with login
    }
    
    console.log('=== Logging in with global test account ===')
    await driver.get(BASE_URL)
    
    // Click Sign In
    const signInButton = await driver.wait(
      until.elementLocated(By.xpath("//button[contains(text(), 'Sign In')]")),
      5000
    )
    await signInButton.click()
    
    // Wait for Auth0 page
    await driver.wait(async () => {
      const url = await driver.getCurrentUrl()
      return url.includes('auth0.com')
    }, 10000)
    
    // Enter email
    const emailInput = await driver.wait(
      until.elementLocated(By.css('input[type="email"], input[name="email"], input[name="username"]')),
      10000
    )
    await emailInput.sendKeys(globalTestEmail)
    
    // Click continue button
    try {
      const continueBtn = await driver.wait(
        until.elementLocated(By.css('button[type="submit"], button[name="action"]')),
        5000
      )
      await continueBtn.click()
      await driver.sleep(2000)
    } catch (e) {
      // No continue button
    }
    
    // Enter password
    const passwordInput = await driver.wait(
      until.elementLocated(By.css('input[type="password"]')),
      5000
    )
    await passwordInput.sendKeys(globalTestPassword)
    
    // Submit login
    const submitButton = await driver.findElement(By.css('button[type="submit"], button[name="action"]'))
    await submitButton.click()
    
    // Handle Auth0 consent screen
    try {
      await driver.sleep(3000)
      const currentUrl = await driver.getCurrentUrl()
      
      if (currentUrl.includes('auth0.com') && (currentUrl.includes('consent') || currentUrl.includes('authorize'))) {
        try {
          const acceptButton = await driver.wait(
            until.elementLocated(By.xpath("//button[contains(., 'Accept')] | //button[contains(., 'Allow')] | //button[contains(., 'Continue')] | //button[@value='accept']")),
            5000
          )
          await acceptButton.click()
        } catch (e) {
          // No accept button
        }
      }
    } catch (e) {
      // No consent screen
    }
    
    // Wait for redirect
    await driver.wait(async () => {
      const url = await driver.getCurrentUrl()
      return url.includes(BASE_URL) && !url.includes('auth0.com')
    }, 15000)
    
    // Verify logged in
    await driver.wait(
      until.elementLocated(By.css('img[alt*="Profile"], div[class*="rounded-full"]')),
      5000
    )
    
    console.log('✓ User logged in successfully')
  }

  beforeEach(async function() {
    const options = new chrome.Options()
    options.addArguments('--disable-blink-features=AutomationControlled')
    options.addArguments('--force-dark-mode=0')
    options.addArguments('--disable-features=PrefersDarkScheme')
    driver = await new Builder()
      .forBrowser('chrome')
      .setChromeOptions(options)
      .build()
    await driver.manage().window().maximize()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Booking Summary Calculation', async function() {
    await loginWithGlobalAccount()
    await driver.get("http://localhost:5173/flight")
    await driver.manage().window().setRect({ width: 1920, height: 1036 })
    await driver.sleep(1500)
    // Click origin airport selector
    const originSelector = await driver.wait(
      until.elementLocated(By.css(".relative:nth-child(1) > .h-12")),
      5000
    )
    await driver.executeScript("arguments[0].scrollIntoView({block: 'center'});", originSelector)
    await driver.sleep(500)
    try {
      await originSelector.click()
    } catch (e) {
      console.log('Click intercepted, using JavaScript click')
      await driver.executeScript("arguments[0].click();", originSelector)
    }
    await driver.sleep(800)
    // Select origin airport from dropdown
    const originOption = await driver.wait(
      until.elementLocated(By.xpath("//div[@id='radix-:r15:']/div/span")),
      5000
    )
    await driver.executeScript("arguments[0].scrollIntoView({block: 'center'});", originOption)
    await driver.sleep(300)
    try {
      await originOption.click()
    } catch (e) {
      await driver.executeScript("arguments[0].click();", originOption)
    }
    await driver.sleep(800)
    // Click destination airport selector
    const destSelector = await driver.wait(
      until.elementLocated(By.css(".relative:nth-child(2) > .h-12")),
      5000
    )
    await driver.executeScript("arguments[0].scrollIntoView({block: 'center'});", destSelector)
    await driver.sleep(500)
    try {
      await destSelector.click()
    } catch (e) {
      console.log('Click intercepted, using JavaScript click')
      await driver.executeScript("arguments[0].click();", destSelector)
    }
    await driver.sleep(800)
    // Select destination airport from dropdown
    const destOption = await driver.wait(
      until.elementLocated(By.xpath("//div[@id='radix-:r33:']/div/span")),
      5000
    )
    await driver.executeScript("arguments[0].scrollIntoView({block: 'center'});", destOption)
    await driver.sleep(300)
    try {
      await destOption.click()
    } catch (e) {
      await driver.executeScript("arguments[0].click();", destOption)
    }
    await driver.sleep(800)
    // Click date selector
    const dateSelector = await driver.wait(
      until.elementLocated(By.css("div:nth-child(3) > .w-full")),
      5000
    )
    await driver.executeScript("arguments[0].scrollIntoView({block: 'center'});", dateSelector)
    await driver.sleep(500)
    try {
      await dateSelector.click()
    } catch (e) {
      console.log('Click intercepted, using JavaScript click')
      await driver.executeScript("arguments[0].click();", dateSelector)
    }
    await driver.sleep(1000)
    const dateInput = await driver.wait(
      until.elementLocated(By.css(".file\\3Atext-foreground")),
      5000
    )
    await dateInput.click()
    await dateInput.sendKeys("2025-12-17")
    await driver.sleep(500)
    await driver.findElement(By.css(".hover\\3Ascale-105")).click()
    // Wait for passenger selector to be available and click it
    await driver.sleep(1000)
    try {
      const passengerSelector = await driver.wait(
        until.elementLocated(By.css(".hover\\3A bg-muted\\/50:nth-child(6) .inline-flex")),
        5000
      )
      await passengerSelector.click()
    } catch (e) {
      console.log('Unable to find passenger selector with original selector, trying alternative...')
      // Try alternative selectors
      try {
        const passengerBtn = await driver.findElement(By.xpath("//button[contains(@class, 'inline-flex')]"))
        await passengerBtn.click()
      } catch (e2) {
        console.log('Alternative selector also failed, continuing...')
      }
    }
    await driver.sleep(500)
    await driver.findElement(By.css(".bg-primary")).click()
    await driver.sleep(1500)
    // Wait for and click the accent element (likely flight selection or similar)
    try {
      const accentElement = await driver.wait(
        until.elementLocated(By.css(".bg-accent\\/20 > .text-lg")),
        5000
      )
      await accentElement.click()
      await driver.actions({ bridge: true }).move({origin: accentElement}).perform()
    } catch (e) {
      console.log('Unable to find element with .bg-accent/20 > .text-lg, trying alternatives...')
      try {
        // Try to find any element with text-lg class in an accent-colored container
        const alternative = await driver.findElement(By.xpath("//div[contains(@class, 'accent')]//div[contains(@class, 'text-lg')]"))
        await alternative.click()
        await driver.actions({ bridge: true }).move({origin: alternative}).perform()
      } catch (e2) {
        console.log('Alternative selector also failed, continuing...')
      }
    }
    await driver.sleep(500)
    const continueBtn = await driver.wait(
      until.elementLocated(By.css(".hover\\3A bg-primary\\/90")),
      5000
    )
    await continueBtn.click()
    await driver.sleep(1000)
    const firstNameInput = await driver.wait(
      until.elementLocated(By.css(".md\\3A col-span-2:nth-child(1) > .file\\3Atext-foreground")),
      5000
    )
    await firstNameInput.click()
    await driver.findElement(By.css(".md\\3A col-span-2:nth-child(1) > .file\\3Atext-foreground")).sendKeys("aba")
    await driver.sleep(300)
    const lastNameInput = await driver.wait(
      until.elementLocated(By.css(".md\\3A col-span-2:nth-child(3) > .file\\3Atext-foreground")),
      5000
    )
    await lastNameInput.click()
    await lastNameInput.sendKeys("aba")
    await driver.sleep(300)
    try {
      const passportInput = await driver.wait(
        until.elementLocated(By.css(".bg-card:nth-child(2) .md\\3A col-span-3:nth-child(4) > .file\\3Atext-foreground")),
        3000
      )
      await passportInput.click()
    } catch (e) {
      console.log('Passport field not found or not required')
    }
    await driver.sleep(300)
    const dobInput = await driver.wait(
      until.elementLocated(By.css(".md\\3A col-span-3:nth-child(5) > .file\\3Atext-foreground")),
      5000
    )
    await dobInput.click()
    await dobInput.click()
    await dobInput.sendKeys("2025-12-23")
    await driver.sleep(300)
    const emailInput = await driver.wait(
      until.elementLocated(By.css(".md\\3A col-span-3:nth-child(6) > .file\\3Atext-foreground")),
      5000
    )
    await emailInput.click()
    await emailInput.sendKeys("example@gmail.com")
    await driver.sleep(300)
    const phoneInput = await driver.wait(
      until.elementLocated(By.css(".md\\3A col-span-3:nth-child(7) > .file\\3Atext-foreground")),
      5000
    )
    await phoneInput.sendKeys("1234567890")
    await driver.sleep(500)
    const emergencyFirstName = await driver.wait(
      until.elementLocated(By.css(".md\\3A col-span-3:nth-child(1) > .file\\3Atext-foreground")),
      5000
    )
    await emergencyFirstName.sendKeys("abac")
    await driver.sleep(300)
    const emergencyLastName = await driver.wait(
      until.elementLocated(By.css(".md\\3A col-span-3:nth-child(2) > .file\\3Atext-foreground")),
      5000
    )
    await emergencyLastName.sendKeys("abac")
    await driver.sleep(300)
    const emergencyEmail = await driver.wait(
      until.elementLocated(By.css(".md\\3A col-span-3:nth-child(3) > .file\\3Atext-foreground")),
      5000
    )
    await emergencyEmail.sendKeys("example@yahoo.com")
    await driver.sleep(300)
    try {
      const emergencyPhone = await driver.wait(
        until.elementLocated(By.css(".bg-card:nth-child(3) .md\\3A col-span-3:nth-child(4) > .file\\3Atext-foreground")),
        5000
      )
      await emergencyPhone.sendKeys("1234567890")
    } catch (e) {
      console.log('Emergency phone field not found with specific selector, trying alternative...')
      try {
        const altPhoneInput = await driver.findElement(By.xpath("(//input[@type='text' or @type='tel'])[last()]"))
        await altPhoneInput.sendKeys("1234567890")
      } catch (e2) {
        console.log('Could not find emergency contact phone field')
      }
    }
    await driver.sleep(1000)
    const submitBtn = await driver.wait(
      until.elementLocated(By.css(".bg-primary")),
      5000
    )
    await submitBtn.click()
  })
})
