// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import assert from 'assert'
import chrome from 'selenium-webdriver/chrome.js'

describe('Passenger Info - Valid Data', function() {
  this.timeout(60000)
  let driver
  let vars
  const BASE_URL = 'http://localhost:5173'
  
  // Global test account credentials from environment variables
  const globalTestEmail = process.env.EMAIL || 'globaltest1765533455848@example.com'
  const globalTestPassword = process.env.PASSWORD || 'TestAccount123!'

  async function loginWithGlobalAccount() {
    await driver.get(BASE_URL)
    
    // Check if already logged in
    try {
      await driver.get(`${BASE_URL}/flight`)
      await driver.sleep(2000)
      
      const currentUrl = await driver.getCurrentUrl()
      if (currentUrl.includes(BASE_URL) && !currentUrl.includes('auth0.com')) {
        try {
          await driver.findElement(By.css('img[alt*="Profile"], div[class*="rounded-full"]'))
          console.log('✓ User already logged in')
          return
        } catch (e) {
          // No profile, need to login
        }
      }
    } catch (e) {
      // Error checking, proceed with login
    }
    
    console.log('=== Logging in with global test account ===')
    await driver.get(BASE_URL)
    
    // Click Sign In
    const signInButton = await driver.wait(
      until.elementLocated(By.xpath("//button[contains(text(), 'Sign In')]")),
      5000
    )
    await signInButton.click()
    
    // Wait for Auth0 page
    await driver.wait(async () => {
      const url = await driver.getCurrentUrl()
      return url.includes('auth0.com')
    }, 10000)
    
    // Enter email
    const emailInput = await driver.wait(
      until.elementLocated(By.css('input[type="email"], input[name="email"], input[name="username"]')),
      10000
    )
    await emailInput.sendKeys(globalTestEmail)
    
    // Click continue button
    try {
      const continueBtn = await driver.wait(
        until.elementLocated(By.css('button[type="submit"], button[name="action"]')),
        5000
      )
      await continueBtn.click()
      await driver.sleep(2000)
    } catch (e) {
      // No continue button
    }
    
    // Enter password
    const passwordInput = await driver.wait(
      until.elementLocated(By.css('input[type="password"]')),
      5000
    )
    await passwordInput.sendKeys(globalTestPassword)
    
    // Submit login
    const submitButton = await driver.findElement(By.css('button[type="submit"], button[name="action"]'))
    await submitButton.click()
    
    // Handle Auth0 consent screen
    try {
      await driver.sleep(3000)
      const currentUrl = await driver.getCurrentUrl()
      
      if (currentUrl.includes('auth0.com') && (currentUrl.includes('consent') || currentUrl.includes('authorize'))) {
        try {
          const acceptButton = await driver.wait(
            until.elementLocated(By.xpath("//button[contains(., 'Accept')] | //button[contains(., 'Allow')] | //button[contains(., 'Continue')] | //button[@value='accept']")),
            5000
          )
          await acceptButton.click()
        } catch (e) {
          // No accept button
        }
      }
    } catch (e) {
      // No consent screen
    }
    
    // Wait for redirect
    await driver.wait(async () => {
      const url = await driver.getCurrentUrl()
      return url.includes(BASE_URL) && !url.includes('auth0.com')
    }, 15000)
    
    // Verify logged in
    await driver.wait(
      until.elementLocated(By.css('img[alt*="Profile"], div[class*="rounded-full"]')),
      5000
    )
    
    console.log('✓ User logged in successfully')
  }

  beforeEach(async function() {
    const options = new chrome.Options()
    options.addArguments('--disable-blink-features=AutomationControlled')
    options.addArguments('--force-dark-mode=0')
    options.addArguments('--disable-features=PrefersDarkScheme')
    driver = await new Builder()
      .forBrowser('chrome')
      .setChromeOptions(options)
      .build()
    await driver.manage().window().maximize()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Passenger Info - Valid Data', async function() {
    await loginWithGlobalAccount()
    await driver.get("http://localhost:5173/flight")
    
    // Wait for page to load
    await driver.sleep(2000)
    
    // Click origin/from field
    const originField = await driver.findElement(By.css(".relative:nth-child(1) > .h-12"))
    await originField.click()
    await driver.sleep(1000)
    console.log('✓ Origin dropdown opened')
    
    // Select first airport option in dropdown (try to get all options)
    const originOptions = await driver.wait(
      until.elementsLocated(By.css("[role='option']")),
      5000
    )
    console.log(`Found ${originOptions.length} origin options`)
    if (originOptions.length > 0) {
      await originOptions[0].click()
      console.log('✓ Origin selected')
    }
    await driver.sleep(1000)
    
    // Click destination/to field
    const destField = await driver.findElement(By.css(".relative:nth-child(2) > .h-12"))
    await destField.click()
    await driver.sleep(1000)
    console.log('✓ Destination dropdown opened')
    
    // Select second destination option in dropdown (avoid same as origin)
    const destOptions = await driver.wait(
      until.elementsLocated(By.css("[role='option']")),
      5000
    )
    console.log(`Found ${destOptions.length} destination options`)
    if (destOptions.length > 1) {
      await destOptions[1].click()
      console.log('✓ Destination selected')
    } else if (destOptions.length > 0) {
      await destOptions[0].click()
      console.log('✓ Destination selected (first option)')
    }
    await driver.sleep(1000)
    
    // Click search button
    await driver.findElement(By.css(".hover\\3Ascale-105")).click()
    {
      const element = await driver.findElement(By.css(".hover\\3Ascale-105"))
      await driver.actions({ bridge: true }).move({origin: element}).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move({x: 0, y: 0}).perform()
    }
    await driver.findElement(By.css("div:nth-child(3) > .h-12")).click()
    {
      const element = await driver.findElement(By.css("div:nth-child(3) > .h-12"))
      await driver.actions({ bridge: true }).move({origin: element}).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move({x: 0, y: 0}).perform()
    }
    await driver.findElement(By.css(".file\\3Atext-foreground")).click()
    await driver.findElement(By.css(".file\\3Atext-foreground")).sendKeys("2025-12-16")
    await driver.findElement(By.css(".hover\\3Ascale-105")).click()
    // Wait for date picker to be visible and clickable
    await driver.sleep(1000)
    try {
      const dateElement = await driver.wait(
        until.elementLocated(By.css(".hover\\3A bg-muted\\/50:nth-child(5) .inline-flex")),
        5000
      )
      await dateElement.click()
    } catch (e) {
      console.log('Date picker element not found, continuing...')
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move({x: 0, y: 0}).perform()
    }
    
    // Click search button
    const searchButton = await driver.wait(
      until.elementLocated(By.css(".bg-primary")),
      5000
    )
    await searchButton.click()
    console.log('✓ Search button clicked')
    
    // Wait for flight results to load
    await driver.sleep(3000)
    console.log('Waiting for flight results...')
    
    try {
      const flightCard = await driver.wait(
        until.elementLocated(By.css(".bg-accent\\/20")),
        15000
      )
      console.log('✓ Flight results found')
      await flightCard.click()
    } catch (e) {
      console.log('Failed to find flight results. Current URL:', await driver.getCurrentUrl())
      throw e
    }
    
    await driver.sleep(2000)
    
    // Wait for the book/continue button to appear
    const bookButton = await driver.wait(
      until.elementLocated(By.css(".hover\\3A bg-primary\\/90")),
      10000
    )
    await bookButton.click()
    await driver.sleep(2000)
    console.log('✓ Navigated to passenger info page')
    
    // Fill in all form fields
    try {
      const formFields = await driver.findElements(By.css("input.file\\3Atext-foreground"))
      console.log(`Found ${formFields.length} form input fields`)
      
      // Fill first name
      if (formFields.length > 0) {
        await formFields[0].click()
        await formFields[0].sendKeys("John")
      }
      
      // Fill last name
      if (formFields.length > 1) {
        await formFields[1].sendKeys("Doe")
      }
      
      // Fill date of birth
      if (formFields.length > 2) {
        await formFields[2].click()
        await formFields[2].sendKeys("1990-01-01")
      }
      
      // Fill email
      if (formFields.length > 3) {
        await formFields[3].click()
        await formFields[3].sendKeys("john.doe@example.com")
      }
      
      // Fill phone number
      if (formFields.length > 4) {
        await formFields[4].sendKeys("1234567890")
      }
      
      // Fill emergency contact name
      if (formFields.length > 5) {
        await formFields[5].sendKeys("Jane")
      }
      
      // Fill emergency contact last name
      if (formFields.length > 6) {
        await formFields[6].sendKeys("Smith")
      }
      
      // Fill emergency contact email
      if (formFields.length > 7) {
        await formFields[7].sendKeys("jane.smith@example.com")
      }
      
      // Fill emergency contact phone
      if (formFields.length > 8) {
        await formFields[8].sendKeys("9876543210")
      }
      
      console.log('✓ All form fields filled')
      await driver.sleep(1000)
      
      // Click submit/continue button
      const submitButton = await driver.wait(
        until.elementLocated(By.css(".hover\\3A bg-primary\\/90")),
        5000
      )
      await submitButton.click()
      console.log('✓ Form submitted')
    } catch (e) {
      console.log('Error filling form:', e.message)
      throw e
    }
  })
})
