// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import assert from 'assert'
import chrome from 'selenium-webdriver/chrome.js'

describe('Passenger Info - Empty Fields', function() {
  this.timeout(60000)
  let driver
  let vars
  const BASE_URL = 'http://localhost:5173'
  
  // Global test account credentials from environment variables
  const globalTestEmail = process.env.EMAIL || 'globaltest1765533455848@example.com'
  const globalTestPassword = process.env.PASSWORD || 'TestAccount123!'

  async function loginWithGlobalAccount() {
    await driver.get(BASE_URL)
    
    // Check if already logged in
    try {
      await driver.get(`${BASE_URL}/flight`)
      await driver.sleep(2000)
      
      const currentUrl = await driver.getCurrentUrl()
      if (currentUrl.includes(BASE_URL) && !currentUrl.includes('auth0.com')) {
        try {
          await driver.findElement(By.css('img[alt*="Profile"], div[class*="rounded-full"]'))
          console.log('✓ User already logged in')
          return
        } catch (e) {
          // No profile, need to login
        }
      }
    } catch (e) {
      // Error checking, proceed with login
    }
    
    console.log('=== Logging in with global test account ===')
    await driver.get(BASE_URL)
    
    // Click Sign In
    const signInButton = await driver.wait(
      until.elementLocated(By.xpath("//button[contains(text(), 'Sign In')]")),
      5000
    )
    await signInButton.click()
    
    // Wait for Auth0 page
    await driver.wait(async () => {
      const url = await driver.getCurrentUrl()
      return url.includes('auth0.com')
    }, 10000)
    
    // Enter email
    const emailInput = await driver.wait(
      until.elementLocated(By.css('input[type="email"], input[name="email"], input[name="username"]')),
      10000
    )
    await emailInput.sendKeys(globalTestEmail)
    
    // Click continue button
    try {
      const continueBtn = await driver.wait(
        until.elementLocated(By.css('button[type="submit"], button[name="action"]')),
        5000
      )
      await continueBtn.click()
      await driver.sleep(2000)
    } catch (e) {
      // No continue button
    }
    
    // Enter password
    const passwordInput = await driver.wait(
      until.elementLocated(By.css('input[type="password"]')),
      5000
    )
    await passwordInput.sendKeys(globalTestPassword)
    
    // Submit login
    const submitButton = await driver.findElement(By.css('button[type="submit"], button[name="action"]'))
    await submitButton.click()
    
    // Handle Auth0 consent screen
    try {
      await driver.sleep(3000)
      const currentUrl = await driver.getCurrentUrl()
      
      if (currentUrl.includes('auth0.com') && (currentUrl.includes('consent') || currentUrl.includes('authorize'))) {
        try {
          const acceptButton = await driver.wait(
            until.elementLocated(By.xpath("//button[contains(., 'Accept')] | //button[contains(., 'Allow')] | //button[contains(., 'Continue')] | //button[@value='accept']")),
            5000
          )
          await acceptButton.click()
        } catch (e) {
          // No accept button
        }
      }
    } catch (e) {
      // No consent screen
    }
    
    // Wait for redirect
    await driver.wait(async () => {
      const url = await driver.getCurrentUrl()
      return url.includes(BASE_URL) && !url.includes('auth0.com')
    }, 15000)
    
    // Verify logged in
    await driver.wait(
      until.elementLocated(By.css('img[alt*="Profile"], div[class*="rounded-full"]')),
      5000
    )
    
    console.log('✓ User logged in successfully')
  }

  beforeEach(async function() {
    const options = new chrome.Options()
    options.addArguments('--disable-blink-features=AutomationControlled')
    options.addArguments('--force-dark-mode=0')
    options.addArguments('--disable-features=PrefersDarkScheme')
    driver = await new Builder()
      .forBrowser('chrome')
      .setChromeOptions(options)
      .build()
    await driver.manage().window().maximize()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Passenger Info - Empty Fields', async function() {
    await loginWithGlobalAccount()
    await driver.get("http://localhost:5173/flight")
    await driver.findElement(By.css(".relative:nth-child(1) > .h-12")).click()
    await driver.findElement(By.xpath("//div[@id=\'radix-:r15:\']/div/span")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .h-12")).click()
    await driver.findElement(By.css("#radix-\\3Ar33\\3A > .flex > .text-sm")).click()
    await driver.findElement(By.css("div:nth-child(3) > .w-full")).click()
    {
      const element = await driver.findElement(By.css("div:nth-child(3) > .w-full"))
      await driver.actions({ bridge: true }).move({origin: element}).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move({x: 0, y: 0}).perform()
    }
    await driver.findElement(By.css(".file\\3Atext-foreground")).sendKeys("2025-12-17")
    await driver.findElement(By.css(".hover\\3Ascale-105")).click()
    // Wait for date picker to be visible and clickable
    await driver.sleep(1000)
    try {
      const dateElement = await driver.wait(
        until.elementLocated(By.css(".hover\\3A bg-muted\\/50:nth-child(5) .inline-flex")),
        5000
      )
      await dateElement.click()
    } catch (e) {
      console.log('Date picker element not found, continuing...')
    }
    // Click search button
    const searchButton = await driver.wait(
      until.elementLocated(By.css(".bg-primary")),
      5000
    )
    await searchButton.click()
    console.log('✓ Search button clicked')
    
    // Wait for flight results to load
    await driver.sleep(3000)
    console.log('Waiting for flight results...')
    
    try {
      const flightCard = await driver.wait(
        until.elementLocated(By.css(".bg-accent\\/20")),
        15000
      )
      console.log('✓ Flight results found')
      await flightCard.click()
    } catch (e) {
      console.log('Failed to find flight results. Current URL:', await driver.getCurrentUrl())
      throw e
    }
    await driver.sleep(2000)
    // Wait for the book/continue button to appear
    const bookButton = await driver.wait(
      until.elementLocated(By.css(".hover\\3A bg-primary\\/90")),
      10000
    )
    await bookButton.click()
    await driver.sleep(1000)
    await driver.findElement(By.css(".md\\3A col-span-2:nth-child(3) > .file\\3Atext-foreground")).click()
    await driver.findElement(By.css(".md\\3A col-span-2:nth-child(3) > .file\\3Atext-foreground")).sendKeys("asdfsa")
    await driver.findElement(By.css(".bg-primary")).click()
    await driver.sleep(500)
    // Verify and dismiss first alert
    assert(await driver.switchTo().alert().getText() == "Please fill in all required fields for Passenger 1")
    await driver.switchTo().alert().accept()
    console.log('✓ First alert verified and dismissed')
    
    await driver.sleep(500)
    await driver.findElement(By.css(".md\\3A col-span-2:nth-child(1) > .file\\3Atext-foreground")).click()
    await driver.findElement(By.css(".md\\3A col-span-2:nth-child(1) > .file\\3Atext-foreground")).sendKeys("abc")
    await driver.findElement(By.css(".bg-primary")).click()
    await driver.sleep(500)
    // Verify and dismiss second alert
    assert(await driver.switchTo().alert().getText() == "Please fill in all required fields for Passenger 1")
    await driver.switchTo().alert().accept()
    console.log('✓ Second alert verified and dismissed')
  })
})
